version: '3.0'

services:

  mysql-server-1:
    hostname: mysql-server-1
    container_name: mysql-server-1
    image: mysql/mysql-server:8.0.32
    env_file:
      - mysql.env
    cap_add:
      - SYS_NICE  
    ports:
      - 3306:3306
      - 33061:33060
    volumes:
      - ${APP_VOLUMES_DIR}/mysql82301:/var/lib/mysql
      - ${APP_CONFIG_DIR}/mysql-server-1.cnf:/etc/my.cnf
    profiles:
      - cluster

  mysql-server-2:
    hostname: mysql-server-2
    container_name: mysql-server-2
    image: mysql/mysql-server:8.0.32
    env_file:
      - mysql.env
    cap_add:
      - SYS_NICE  
    ports:
      - 3307:3306
      - 33062:33060
    volumes:
      - ${APP_VOLUMES_DIR}/mysql8032:/var/lib/mysql
      - ${APP_CONFIG_DIR}/mysql-server-2.cnf:/etc/my.cnf
    profiles:
      - cluster

  mysql-server-3:
    hostname: mysql-server-3
    container_name: mysql-server-3
    image: mysql/mysql-server:8.0.32
    env_file:
      - mysql.env
    cap_add:
      - SYS_NICE  
    ports:
      - 3308:3306
      - 33063:33060
    volumes:
      - ${APP_VOLUMES_DIR}/mysql82303:/var/lib/mysql
      - ${APP_CONFIG_DIR}/mysql-server-3.cnf:/etc/my.cnf
    profiles:
      - cluster

  proxysql-2.4:
    container_name: proxysql
    hostname: proxysql
    image: proxysql/proxysql:2.4.8
    ports:
      - 6032:6032
      - 6033:6033
      - 6070:6070
    volumes:
      - ${APP_VOLUMES_DIR}/proxysql24:/var/lib/proxysql
    profiles:
      - cluster

  mysql-router:
    hostname: mysql_router
    container_name: mysql-router
    command: "tail -f /etc/hosts"
    image: mysql-router-shell
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    profiles:
      - cluster

  proxysql-cluster:
    container_name: proxysql
    hostname: proxysql
    image: proxysql/proxysql:2.4.4
    ports:
      - 6032:6032
      - 6033:6033
      - 6070:6070
    volumes:
      - ${APP_VOLUMES_DIR}/proxysql2.4gr:/var/lib/proxysql
    profiles:
      - cluster
      

networks:
  defaults:
    name: sysown-internal
    external: true

